GET {{hostname}}/healthcheck

###
POST {{hostname}}/todo/signup
Content-Type: application/json

{
    "title": "Ford interview",
    "description": "scheduled final stage interview for bentley inc",
    "start_at": "2023-12-20 13:00:00",
    "end_at": "2023-12-20 13:30:00"
}

###
GET {{hostname}}/todo
Content-Type: application/json

###
GET {{hostname}}/todo/4
Content-Type: application/json

###
PATCH {{hostname}}/2
Content-Type: application/json

{
    "title": "study",
    "description": "upcoming google interview",
    "start_at": "2023-11-22 14:00:00",
    "end_at": "2023-11-22 17:45:00"
}

###
DELETE {{hostname}}/2
Content-Type: application/json
