GET {{hostname}}/healthcheck

###
POST {{hostname}}/signup
Content-Type: application/json

{
    "title": "grocery runs",
    "description": "restock toiletries and kitchen restock from keflers stores by boulevard ave",
    "start_at": "2023-11-19 19:15:00",
    "end_at": "2023-11-19 20:30:00"
}

###
GET {{hostname}}
Content-Type: application/json

###
GET {{hostname}}/3
Content-Type: application/json

###
PATCH {{hostname}}/2
Content-Type: application/json

{
    "title": "study",
    "description": "upcoming google interview",
    "start_at": "2023-11-22 14:00:00",
    "end_at": "2023-11-22 17:45:00"
}

###
DELETE {{hostname}}/2
Content-Type: application/json
