GET {{hostname}}/healthcheck

###
POST {{hostname}}/todo/add
Content-Type: application/json

{
    "title": "Ford interview",
    "description": "scheduled final stage interview for bentley inc",
    "start_at": "2023-12-20 13:00:00",
    "end_at": "2023-12-20 13:30:00"
}

###
GET {{hostname}}/todo
Content-Type: application/json

###
GET {{hostname}}/todo/4
Content-Type: application/json

###
PATCH {{hostname}}/2
Content-Type: application/json

{
    "title": "study",
    "description": "upcoming google interview",
    "start_at": "2023-11-22 14:00:00",
    "end_at": "2023-11-22 17:45:00"
}

###
DELETE {{hostname}}/2
Content-Type: application/json

###
POST {{hostname}}/api/user/signup
Content-Type: application/json

{
    "username": "bebo",
    "fullname": "ashiru habeeb adewale",
    "e-mail": "ashiruhabeeb@gmail.com",
    "password": "sonybRavia92P",
    "confirm_password": "sonybRavia92P",
    "phone": "+2347059254137"
}

###
POST {{hostname}}/api/user/signup/verifyotp
Content-Type: application/json

{
    "user": {
        "phoneNumber": "+2347059254137"
    },
    "code": "828962"
}